"""empty message

Revision ID: 7ca0d290a1fd
Revises: a34ae2a8ff23
Create Date: 2022-05-10 23:08:43.894794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca0d290a1fd'
down_revision = 'a34ae2a8ff23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
